### ISSUE TITLE
Auto-Form Fill Out

### ISSUE THREAD

**Issue by avoorhees** [Cloudbakers/PharmaCannis-Virtual-Gateway#2]
Given I am user
When I click the chrome extension
Then a form should be filled out on the page. Also, the extension needs to be able to "click" a button on the page.

For this issue, set up a simple html page so you can get the basic functionality working. Ideally, we write helper functions like `input_data(id_of_element, text)` so that when we get access to the actual form, it's not a big refactoring. 

This is just the first iteration of the auto-filling. It will change when we get more information from NAV and start actually filling out the real form.

**Comment by alexwennerberg** [comment]
Created basic demo in da9c3c1760bdd: filling out username / passwords in hackernews
