### ISSUE TITLE
Chrome Extension Set Location

### ISSUE THREAD

**Issue by avoorhees** [Cloudbakers/PharmaCannis-Virtual-Gateway#3]
Given I am a user 
When I  just logged on to the computer
Then I should be able to click the extension, input my station number, and press save. At this point, the station ID will save in the chrome extension (probably using local storage).

We need to know the station ID when calling the NAV API. Each transaction in the NAV API will be tied to a station ID. The user should only have to input this once, but should be able change it as well. 

We need to do research on best way to handle config in chrome extensions. Is it on a separate html page that loads up? Or can you expand a little widget from the extension. Browser stack does that. 
<img width="528" alt="screen shot 2018-06-14 at 4 12 35 pm" src="https://user-images.githubusercontent.com/5651048/41438692-c5431824-6fed-11e8-85c2-fe7f36889063.png">

And OneTab opens a new HTML page.

<img width="1277" alt="screen shot 2018-06-14 at 4 12 51 pm" src="https://user-images.githubusercontent.com/5651048/41438713-d1bc041c-6fed-11e8-977d-d63275e1b467.png">

**Comment by alexwennerberg** [comment]
Added in 35b6b7b

![screen shot 2018-06-20 at 11 20 52 am](https://user-images.githubusercontent.com/11624958/41671232-1b75b1b0-747c-11e8-9350-7387de662791.png)

**Comment by avoorhees** [comment]
@alexwennerberg is that a new page or a popup?

**Comment by alexwennerberg** [comment]
popup when u click the icon
